# Name of your workflow
name: CI/CD Pipeline for Node.js App

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [ "main" ]

# Define the jobs that will be executed
jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aksarsr/cicd-node-app:latest  # ← Replace with your actual Docker Hub repo if different

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Step 1: SSH into EC2 and deploy the new image
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull aksarsr/cicd-node-app:latest  # ← Replace if your repo is different

            # Stop the existing container if running
            docker stop my-node-app || true

            # Remove the old container
            docker rm my-node-app || true

            # Run the new container
            docker run -d --name my-node-app -p 80:3000 aksarsr/cicd-node-app:latest  # ← Update if needed
